config/routes.rb
Walkingthepath::Application.routes.draw do
  root :to => "events#index"
  resources :events
  match '/auth/twitter/callback' => 'users#authentication'
end

app/models/event.rb
#encoding: utf-8
require 'date'

class Event < ActiveRecord::Base

  has_one :slot

  validates_presence_of :title, :message => "No seas vaguete y ponle un título al evento."
  validates_presence_of :link, :message => "Seguro que tienes un enlace a la descripción del evento por algún lado."
  validates_presence_of :slot, :message => "Seguro que sabes cuando se celebrará el evento."
  validates_associated :slot

  validate :event_link_must_be_a_url

  def self.for_today
    Slot.for_today.map(&:event)
  end

  def self.for_tomorrow
    Slot.for_tomorrow.map(&:event)
  end

  def self.in_the_future
    Slot.in_the_future.map(&:event)
  end

  delegate :month, :day, :time, :to => :slot

  def when
    "#{day} de #{month} a las #{time}"
  end

  def error_for(field)
    errors[field].first
  end

  private

  def event_link_must_be_a_url
    errors.add(:link, "Creo que el enlace que has escrito no es correcto. ¡Casi lo tienes!") if not link.blank? and invalid link
  end

  def invalid url
    begin
      uri_class = URI.parse(url).class
      return true if uri_class != URI::HTTP and uri_class != URI::HTTPS
    rescue URI::InvalidURIError
      return true
    end
    false
  end

end

app/models/event_date.rb
class EventDate

  MONTHS = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
  DATE_TIME_FORMAT = '%Y%m%d%H%M'

  def self.now
    DateTime.now
  end

  def initialize(date)
    @date = date
  end

  def year
    @date.year
  end

  def month
    MONTHS[@date.month - 1]
  end

  def day
    @date.day
  end

  def time
    return '---' if undetermined_hour?
    "#{hours}:#{minutes}"
  end

  def to_i
    @date
  end

  def date_time
    @date
  end
  private

  def undetermined_hour?
    @date.hour == 0 && @date.min == 0
  end

  def hours
    "0#{@date.hour}".slice(-2..-1)
  end

  def minutes
    "0#{@date.min}".slice(-2..-1)
  end
end

app/models/slot.rb
class Slot < ActiveRecord::Base

  belongs_to :event

  scope :for_today, where("datetime >= :today AND datetime < :tomorrow", :today => DateTime.now, :tomorrow => DateTime.tomorrow)
  scope :for_tomorrow, where("datetime >= :tomorrow AND datetime < :two_days_ahead", :tomorrow => DateTime.tomorrow, :two_days_ahead => DateTime.tomorrow + 1.day)
  scope :to_come, where("datetime > :today", :today => DateTime.now)
  scope :ordered_by_date, order('datetime ASC')

  validates_presence_of :datetime, :message => "Seguro que sabes cuando se celebrará el evento."
  validate :date_must_be_in_the_future

  def self.in_the_future
    Slot.to_come.ordered_by_date
  end

  MONTHS = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']

  def year
    datetime.year
  end

  def month
   Slot::MONTHS[datetime.month - 1]
  end

  def day
    datetime.day
  end

  def time
    return '---' if undefined_time
    "#{hours}:#{minutes}"
  end

  def error_for(field)
    errors[field].first
  end

  def datetime_as_string
    return '' unless datetime
    return datetime.to_s(:without_time) if undefined_time
    datetime.to_s(:walking)
  end

  def datetime_as_string=(value)
    write_datetime(value)
  rescue
  end

  private

  def write_datetime(value)
    write_attribute(:datetime, DateTime.strptime(value, "%d/%m/%Y %H:%M"))
  rescue
    write_datetime_with_undefined_time(value)
  end

  def write_datetime_with_undefined_time(value)
    write_attribute(:datetime, DateTime.strptime(value, "%d/%m/%Y"))
    write_attribute(:undefined_time, true)
  rescue
  end

  def hours
    "0#{datetime.hour}".slice(-2..-1)
  end

  def minutes
    "0#{datetime.min}".slice(-2..-1)
  end

  def date_must_be_in_the_future
    errors.add(:datetime, "La fecha del evento ya ha pasado, ¡Ojo!") if datetime and Time.now > datetime
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_from_authentication(auth_info)
    user = User.new
    user.provider = auth_info['provider']
    user.uid = auth_info['uid']
    user.name = auth_info['user_info']['name']
    user.save
    user
  end

end

app/models/walking_on_twitter.rb
#encode: utf-8
class WalkingOnTwitter
  def self.update
    self.tweet_today_events
    self.tweet_tomorrow_events
  end

  def self.tweet_today_events
    Event.for_today.each do |event|
      Twitter.update(message_for_today(event))
    end
  end

  def self.tweet_tomorrow_events
    Event.for_tomorrow.each do |event|
      Twitter.update(message_for_tomorrow(event))
    end
  end

  def self.message_for_today(event)
    self.message_for('Hoy', event)
  end

  def self.message_for_tomorrow(event)
    self.message_for('Mañana', event)
  end

  def self.message_for(day, event)
    message = "#{day} a las #{event.time}, #{event.title}. Más información en #{short(event.link)} #{cheering_message}"
    return message if message.size <= 140
    message = "#{day} a las #{event.time}, #{event.title}. #{cheering_message}" if message.size <= 140
    "#{day} #{event.title}"
  end

  def self.cheering_message
    messages = ['¡No puedes faltar!', '¿Te lo vas a perder?', '¡No te lo pierdas!', '¡No faltes!', '¡Va a ser la caña!']
    messages[rand(messages.size)]
  end

  def self.short(url)
    Googl.shorten(url).short_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
#encoding: utf-8
class EventsController < ApplicationController
  include EventsHelper

  before_filter :assert_user_is_authenticated, :only => [:new, :create]

  def index
    @events = Event.in_the_future
    respond_to do |format|
      format.html
      format.atom{render :action => 'index', :layout => false}
    end
  end

  def show
    redirect_to Event.find(params[:id]).link
  end

  def new
    @event = Event.new
    @event.build_slot
  end

  def create
    @event = Event.new params[:event]
    slot = @event.build_slot params[:slot]
    if @event.save
      redirect_to events_path
    else
      flash[:notice] = []
      flash[:notice] << @event.errors[:title].first unless @event.errors[:title].empty?
      flash[:notice] << @event.errors[:link].first unless @event.errors[:link].empty?
      unless slot.valid?
        flash[:notice] << slot.errors[:datetime].first unless slot.errors[:datetime].empty?
      end
      render :new
    end
  end

  private

  def assert_user_is_authenticated
    redirect_to events_path unless user_identified?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def authentication
      session[:user_id] = user_from(request.env["omniauth.auth"]).id
      redirect_to events_path
    end

    private

    def user_from(auth_info)
      User.find_by_provider_and_uid(auth_info['provider'], auth_info['uid']) || User.create_from_authentication(auth_info)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def user_identified?
    session[:user_id].present? or Rails.env == 'development'
  end
end

app/views/events/_authentication.haml
- if session[:user_id].nil?
  %header#sign_in
    .wrapper
      %p
        ¿Quieres crear un nuevo evento?
        = link_to("Identifícate con twitter", "/auth/twitter")
-else
  %header#signed_in
    .wrapper
      - user_name = User.find(session[:user_id]).name
      %p
        Bienvenido, 
        %span
          = user_name

app/views/events/_event.haml
.event{:id => "event_#{event.id}"}
  = render 'event_date', :event => event
  = render 'event_description', :event => event

app/views/events/_event_date.haml
.event_date
  .calendar_date
    %span.month
      #{event.month}
    %span.day
      #{event.day}
  .time
    #{event.time}

app/views/events/_event_description.haml
.h2
  = link_to(event.title, event.link)

app/views/events/_events.haml
#events
  .events
    = render 'feed'
    .content
      - if events.empty?
        Ningún evento próximamente :(
      - else
        = render :partial => 'event', :collection => events

app/views/events/_feed.haml
%header#feeds
  .content
    %h1
      %span.feed
        %a{:href => '/events.atom'}
          Feed de eventos
          %img{:src => 'images/icon_atom.jpg', :alt => 'Feed de eventos'}

app/views/events/_new_event.haml
#add_event
  .wrapper
    #new_event_action
      = link_to("Añadir un evento", new_event_path)

app/views/events/index.haml
.wrapper
  #intro
    .wrapper
      = link_to("Let's walk the path together!", '')
      nace para recopilar los eventos relacionados con el desarrollo de software que van surgiendo por toda España.
      %br
      %br
      ¡Acércate a la comunidad española de desarrolladores!

  = render 'new_event' if user_identified?
  = render 'events', :events => @events

app/views/events/new.haml
- unless notice.nil? or notice.empty?
  - errors = notice.map(&:downcase).join(' Además, ')
  - errors[0] = errors.slice(0,1).capitalize
  #notice= errors
#new_event
  #title
    ¡Vas a crear un nuevo evento, mola!
  = form_for(@event, :url => {:action => 'create'}) do |form|
    #event_details
      .form_field
        = form.text_field(:title)
        = form.label(:title, 'Título')

      .form_field
        = form.text_field(:link)
        = form.label(:link, 'Web')

      #event_slot
        = fields_for @event.slot do |slot_form|
          #event_date
            .form_field
              = slot_form.text_field(:datetime_as_string, :value => @event.slot.datetime_as_string)
              = slot_form.label(:datetime_as_string, 'Fecha y hora')
              .help
                (DD/MM/AAAA [HH:MM])
    = form.submit('Crear Evento')

app/views/layouts/application.haml
!!! HTML
%html{ "xml:lang" => "en"}
  %head
    %title
      Let's walk the path together!
    //= stylesheet_link_tag 'styles.css', :cache => true 
    = auto_discovery_link_tag(:atom, "/events.atom")
    %link{:rel =>"stylesheet", :href =>"/stylesheets/styles.css", :type => "text/css", :charset => "utf-8" }
    %link{:rel =>"author", :href =>"/humans.txt", :type => "text/plain", :charset => "utf-8" }
    %meta{"http-equiv" => "Content-Type", :content => "text/html; charset=UTF-8"}
    %meta{:name => 'description', :content => 'Eventos sin ánimo de lucro relacionados con la comunidad de desarrollo de software española'}
  %body
    = render 'shared/header'
    = render 'authentication'
    = yield
    = render 'shared/analytics' if Rails.env == 'production'

app/views/shared/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-11305746-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_header.haml
%header#header
  .wrapper
    %h1
      Let's walk the path together!

app/views/site/events.haml
.wrapper
  #intro
    .wrapper
      %a{:href => "#"}= "Let's walk the path together!"
      nace para recopilar los eventos relacionados con el desarrollo de software que van surgiendo por toda España.
      %br
      %br
      ¡Acércate a la comunidad española de desarrolladores!

  #events
    .wrapper
      .wrapper
        - if @events.empty?
          Ningún evento próximamente :(
        - else
          - @events.each do |event|
            .datebox
              %span.month
                #{event.month}
              %span.day
                #{event.day}
              %span.time
                #{event.hour}
            .event
              %a{:href => event.link}= event.title

  #add_event
    .wrapper
      Si quieres que un evento aparezca aquí contáctame en
      %a{:href => "http://twitter.com/"}= "twitter"
      , soy 
      %a{:href => "http://twitter.com/plagelao"}= "@plagelao"
    El único que puede añadir eventos a 
    %a{:href => "#"}= "Let's walk the path together!"
    por ahora soy yo, aunque intentaré cambiar ésto lo antes posible